* 我的emacs配置

** 特点
+ 使用 =evil=
+ 参考 =doom-emacs= 配置，优化启动和使用速度
+ 使用 =which-key=
+ 使用 =general=
+ 使用 =ivy + counsel + swiper + ivy-rich=
+ 参考原生的 =deeper-blue= 主题，定制的doom-theme
+ 使用 =doom-modeline=

** evil
*** 使用emacs原生undo-redo
emacs在28.0以后加入了 =undo-redo= , 替换掉 =undo-tree= ，优化速度。

** diredfl
=diredfl= 比较轻量化，如果直接用 =dired= ，文件的不同属组的读写属性只有一个颜色，看着不够美观。

用过 =dired-k= ，在和git一起用的时候，windows上速度有点慢。

** 性能优化

*** gcmh

*** 显示优化

** amx
修改了快捷键的高亮。不知道最新的amx是否有优化。

https://github.com/georgealbert/amx

+ 参考
  https://github.com/DarwinAwardWinner/amx

** org
配置在 =init-org.el= 中。org的配置是很久以前学习的，太多了，实在是不想也不敢改，工作量太大，现在能用，不优化了。

+ 参考
  http://doc.norang.ca/org-mode.html

** UI
*** theme
theme/doom-deeper-blue.el

emacs原生 =deeper-blue= theme 在doom-theme中，org-mode、helm的显示不好看，大改了一番。

** ivy
*** 可以使用拼音字母缩写查询
=C-s= 后，输入 =:cs=


** ime自动切换

*** windows
在windows上写了2个函数，已commit到emacs master分支，在最新的pretest中已经可以体验，在使用微软拼音时效果很不错。

*** macos
没commit到emacs。参考了 =emacs mac port= 的代码。不能在输入法内切换中英文，只能在切换到normal mode时切换到英文输入法，按i或a切换到insert mode时，会切换到rime。

+ 使用macism进程调用时，不太正常。

+ lsp-mode时，用的时间长了，可能会有乱码，只能关闭emacs，重新打开。


